/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/base.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/base.pb-c.h"
void   dias__request_header__init
                     (Dias__RequestHeader         *message)
{
  static const Dias__RequestHeader init_value = DIAS__REQUEST_HEADER__INIT;
  *message = init_value;
}
size_t dias__request_header__get_packed_size
                     (const Dias__RequestHeader *message)
{
  assert(message->base.descriptor == &dias__request_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dias__request_header__pack
                     (const Dias__RequestHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dias__request_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dias__request_header__pack_to_buffer
                     (const Dias__RequestHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dias__request_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dias__RequestHeader *
       dias__request_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dias__RequestHeader *)
     protobuf_c_message_unpack (&dias__request_header__descriptor,
                                allocator, len, data);
}
void   dias__request_header__free_unpacked
                     (Dias__RequestHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dias__request_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dias__reply_header__init
                     (Dias__ReplyHeader         *message)
{
  static const Dias__ReplyHeader init_value = DIAS__REPLY_HEADER__INIT;
  *message = init_value;
}
size_t dias__reply_header__get_packed_size
                     (const Dias__ReplyHeader *message)
{
  assert(message->base.descriptor == &dias__reply_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dias__reply_header__pack
                     (const Dias__ReplyHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dias__reply_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dias__reply_header__pack_to_buffer
                     (const Dias__ReplyHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dias__reply_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dias__ReplyHeader *
       dias__reply_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dias__ReplyHeader *)
     protobuf_c_message_unpack (&dias__reply_header__descriptor,
                                allocator, len, data);
}
void   dias__reply_header__free_unpacked
                     (Dias__ReplyHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dias__reply_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dias__request_header__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Dias__RequestHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dias__RequestHeader, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dias__request_header__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
};
static const ProtobufCIntRange dias__request_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dias__request_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dias.RequestHeader",
  "RequestHeader",
  "Dias__RequestHeader",
  "dias",
  sizeof(Dias__RequestHeader),
  2,
  dias__request_header__field_descriptors,
  dias__request_header__field_indices_by_name,
  1,  dias__request_header__number_ranges,
  (ProtobufCMessageInit) dias__request_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dias__reply_header__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Dias__ReplyHeader, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dias__reply_header__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange dias__reply_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dias__reply_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dias.ReplyHeader",
  "ReplyHeader",
  "Dias__ReplyHeader",
  "dias",
  sizeof(Dias__ReplyHeader),
  1,
  dias__reply_header__field_descriptors,
  dias__reply_header__field_indices_by_name,
  1,  dias__reply_header__number_ranges,
  (ProtobufCMessageInit) dias__reply_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
