/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/keymngr.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "proto/keymngr.pb-c.h"
void   dias__fresh_data_auth_key__init
                     (Dias__FreshDataAuthKey         *message)
{
  static const Dias__FreshDataAuthKey init_value = DIAS__FRESH_DATA_AUTH_KEY__INIT;
  *message = init_value;
}
size_t dias__fresh_data_auth_key__get_packed_size
                     (const Dias__FreshDataAuthKey *message)
{
  assert(message->base.descriptor == &dias__fresh_data_auth_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dias__fresh_data_auth_key__pack
                     (const Dias__FreshDataAuthKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dias__fresh_data_auth_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dias__fresh_data_auth_key__pack_to_buffer
                     (const Dias__FreshDataAuthKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dias__fresh_data_auth_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Dias__FreshDataAuthKey *
       dias__fresh_data_auth_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Dias__FreshDataAuthKey *)
     protobuf_c_message_unpack (&dias__fresh_data_auth_key__descriptor,
                                allocator, len, data);
}
void   dias__fresh_data_auth_key__free_unpacked
                     (Dias__FreshDataAuthKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dias__fresh_data_auth_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dias__fresh_data_auth_key__field_descriptors[2] =
{
  {
    "key_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Dias__FreshDataAuthKey, key_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Dias__FreshDataAuthKey, key_value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dias__fresh_data_auth_key__field_indices_by_name[] = {
  0,   /* field[0] = key_id */
  1,   /* field[1] = key_value */
};
static const ProtobufCIntRange dias__fresh_data_auth_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dias__fresh_data_auth_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dias.FreshDataAuthKey",
  "FreshDataAuthKey",
  "Dias__FreshDataAuthKey",
  "dias",
  sizeof(Dias__FreshDataAuthKey),
  2,
  dias__fresh_data_auth_key__field_descriptors,
  dias__fresh_data_auth_key__field_indices_by_name,
  1,  dias__fresh_data_auth_key__number_ranges,
  (ProtobufCMessageInit) dias__fresh_data_auth_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
