/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: proto/keymngr.proto */

#ifndef PROTOBUF_C_proto_2fkeymngr_2eproto__INCLUDED
#define PROTOBUF_C_proto_2fkeymngr_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Dias__FreshDataAuthKey Dias__FreshDataAuthKey;


/* --- enums --- */


/* --- messages --- */

/*
 * New key issued - option
 */
struct  _Dias__FreshDataAuthKey
{
  ProtobufCMessage base;
  uint32_t key_id;
  char *key_value;
};
#define DIAS__FRESH_DATA_AUTH_KEY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dias__fresh_data_auth_key__descriptor) \
    , 0, NULL }


/* Dias__FreshDataAuthKey methods */
void   dias__fresh_data_auth_key__init
                     (Dias__FreshDataAuthKey         *message);
size_t dias__fresh_data_auth_key__get_packed_size
                     (const Dias__FreshDataAuthKey   *message);
size_t dias__fresh_data_auth_key__pack
                     (const Dias__FreshDataAuthKey   *message,
                      uint8_t             *out);
size_t dias__fresh_data_auth_key__pack_to_buffer
                     (const Dias__FreshDataAuthKey   *message,
                      ProtobufCBuffer     *buffer);
Dias__FreshDataAuthKey *
       dias__fresh_data_auth_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dias__fresh_data_auth_key__free_unpacked
                     (Dias__FreshDataAuthKey *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Dias__FreshDataAuthKey_Closure)
                 (const Dias__FreshDataAuthKey *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dias__fresh_data_auth_key__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_proto_2fkeymngr_2eproto__INCLUDED */
