# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/keymngr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/keymngr.proto',
  package='dias',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13proto/keymngr.proto\x12\x04\x64ias\"5\n\x10\x46reshDataAuthKey\x12\x0e\n\x06key_id\x18\x01 \x02(\r\x12\x11\n\tkey_value\x18\x02 \x02(\t')
)




_FRESHDATAAUTHKEY = _descriptor.Descriptor(
  name='FreshDataAuthKey',
  full_name='dias.FreshDataAuthKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key_id', full_name='dias.FreshDataAuthKey.key_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_value', full_name='dias.FreshDataAuthKey.key_value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['FreshDataAuthKey'] = _FRESHDATAAUTHKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FreshDataAuthKey = _reflection.GeneratedProtocolMessageType('FreshDataAuthKey', (_message.Message,), dict(
  DESCRIPTOR = _FRESHDATAAUTHKEY,
  __module__ = 'proto.keymngr_pb2'
  # @@protoc_insertion_point(class_scope:dias.FreshDataAuthKey)
  ))
_sym_db.RegisterMessage(FreshDataAuthKey)


# @@protoc_insertion_point(module_scope)
