version: "3.7"

services:
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - monitor_network
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  connector:
    image: mrki102/hono-influxdb-connector
    container_name: hono-influxdb-connector
    command: --hono.client.tlsEnabled=true --hono.client.username=messaging@${HONO_TENANTID} --hono.client.password=${HONO_MESSAGINGPW} --tenant.id=${HONO_TENANTID} --server.url=${INFLUXDB_URL} --username=${INFLUXDB_USERNAME} --password=${INFLUXDB_PASSWORD} --database=${INFLUXDB_DATABASE} --nox.map.mode=${EVALUATION_TARGET} --eval.point=${EVALUATION_POINT}
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitor_network
    depends_on:
      - influxdb

  grafana:
    image: grafana/grafana:6.0.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor_network
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=natel-plotly-panel,vonage-status-panel # to add plugins
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana_config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana_config/grafana-provisioning/:/etc/grafana/provisioning/

  diagnostics:
    image: mrki102/diagnostics
    container_name: diagnostics
    command: --server.url=${INFLUXDB_URL} --username=${INFLUXDB_USERNAME} --password=${INFLUXDB_PASSWORD} --database=${INFLUXDB_DATABASE} --nox.map.mode=${EVALUATION_TARGET} --eval.point=${EVALUATION_POINT} --pre.eval.disabled=${PRE_EVALUATION_DISABLED} --modified.classifier=${MODIFIED_CLASSIFIER} --spring.config.location=optional:/config/config.properties
    restart: always
    ports:
      - "4040:4040"
    networks:
      - monitor_network
    volumes:
      - ${CONFIG_PROPERTIES_LOCATION}:/config/
    depends_on:
      - influxdb

networks:
  monitor_network:

volumes:
  influxdb-storage:
  grafana-storage:

# docker-compose up -d
# docker-compose down
# docker-compose down --volumes
