# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ghost_protocol/base.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ghost_protocol/base.proto',
  package='ghost',
  syntax='proto2',
  serialized_options=b'\n\032eu.ghost_iot.communication',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19ghost_protocol/base.proto\x12\x05ghost\")\n\rRequestHeader\x12\n\n\x02id\x18\x01 \x02(\x04\x12\x0c\n\x04name\x18\x02 \x02(\t\"\x19\n\x0bReplyHeader\x12\n\n\x02id\x18\x01 \x02(\x04\x42\x1c\n\x1a\x65u.ghost_iot.communication'
)




_REQUESTHEADER = _descriptor.Descriptor(
  name='RequestHeader',
  full_name='ghost.RequestHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ghost.RequestHeader.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ghost.RequestHeader.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=77,
)


_REPLYHEADER = _descriptor.Descriptor(
  name='ReplyHeader',
  full_name='ghost.ReplyHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ghost.ReplyHeader.id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['RequestHeader'] = _REQUESTHEADER
DESCRIPTOR.message_types_by_name['ReplyHeader'] = _REPLYHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestHeader = _reflection.GeneratedProtocolMessageType('RequestHeader', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTHEADER,
  '__module__' : 'ghost_protocol.base_pb2'
  # @@protoc_insertion_point(class_scope:ghost.RequestHeader)
  })
_sym_db.RegisterMessage(RequestHeader)

ReplyHeader = _reflection.GeneratedProtocolMessageType('ReplyHeader', (_message.Message,), {
  'DESCRIPTOR' : _REPLYHEADER,
  '__module__' : 'ghost_protocol.base_pb2'
  # @@protoc_insertion_point(class_scope:ghost.ReplyHeader)
  })
_sym_db.RegisterMessage(ReplyHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
